FROM python:3.7.3-alpine
MAINTAINER hayatek

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /requirements.txt
RUN apk add --no-cache --virtual .tmp postgresql-client \
    gcc g++ make gfortran openblas-dev linux-headers \
    linux-headers postgresql-dev
RUN pip3 install --upgrade pip
RUN python3.7 -m pip install cython
RUN pip3 install 'numpy==1.17.4'
RUN pip3 install --no-cache-dir 'pandas==0.25.3' --no-build-isolation
RUN pip3 install -r /requirements.txt
RUN apk add gettext-dev

RUN mkdir /app
WORKDIR /app

#ARG USER_ID=1000
#ARG GROUP_ID=1000

#RUN adduser -D myuser -u ${USER_ID} -G mygroup -s /bin/sh -h /

#RUN addgroup -g ${GROUP_ID} mygroup \
#  && adduser -D myuser -u ${USER_ID} -g myuser -G mygroup -s /bin/sh -h /


COPY --chown=1000:1000 . .
#COPY . .

#RUN adduser -D user
#USER user
#CMD bash -c "chmod -R 777 /app -D FOREGROUND"
#CMD gunicorn --bind 0.0.0.0:$PORT config.wsgi
