# Generated by Django 2.2.5 on 2019-09-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190922_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starhistory',
            name='monthly_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
