# Generated by Django 2.2.5 on 2019-09-22 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190922_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starhistory',
            old_name='repository_name',
            new_name='name_owner',
        ),
        migrations.AlterUniqueTogether(
            name='starhistory',
            unique_together={('id', 'name_owner')},
        ),
    ]
