version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
