# Generated by Django 2.2.1 on 2019-06-09 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_id', models.IntegerField()),
                ('name_owner', models.CharField(max_length=100)),
                ('avatar_url', models.CharField(max_length=255)),
                ('resource_path', models.CharField(max_length=255)),
                ('created_at_github', models.DateTimeField(blank=True, null=True)),
                ('updated_at_github', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(max_length=50)),
                ('star_count', models.IntegerField()),
            ],
            options={
                'db_table': 'repository',
            },
        ),
    ]
