# Generated by Django 2.2.2 on 2019-06-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190616_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='database_id',
            field=models.IntegerField(default=0),
        ),
    ]
