# Generated by Django 2.2.5 on 2019-09-22 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_starhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starhistory',
            old_name='repository_id',
            new_name='repository_name',
        ),
        migrations.AlterUniqueTogether(
            name='starhistory',
            unique_together={('id', 'repository_name')},
        ),
        migrations.RemoveField(
            model_name='starhistory',
            name='name_owner',
        ),
    ]
