# Generated by Django 2.2.5 on 2019-09-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190922_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starhistory',
            old_name='name_owner',
            new_name='repository_id',
        ),
        migrations.AlterUniqueTogether(
            name='starhistory',
            unique_together={('id', 'repository_id')},
        ),
    ]
