# Generated by Django 2.2.5 on 2019-09-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190922_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starhistory',
            old_name='repository_id',
            new_name='repository',
        ),
        migrations.AlterUniqueTogether(
            name='starhistory',
            unique_together=set(),
        ),
    ]
